services:
  postgres:
    container_name: postgres
    build:
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./volumes/postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./volumes/postgres/config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./volumes/postgres/config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    restart: unless-stopped
    networks:
      - main
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - GLOBALLY_DELIVERABLE=False

    restart: unless-stopped
    networks:
      - main

volumes:
  postgres_data:
  pgadmin_data:

networks:
  main:
    driver: bridge
